### ISSUE TITLE
我可不可以润色一个自己的版本？

### ISSUE THREAD

**Issue by DEAGS3000** [tkchu/Game-Programming-Patterns-CN#11]
非常感谢您的工作，给我们提供了很大的便利。您的翻译完成度已经很高了，但是我个人实在是讨厌在中文尤其是长句子中使用英文式的插入语，读起来比较拗口，所以我想在您的工作的基础上对照英文版润色一个自己的版本放到网站上去，您觉得可以吗？

**Comment by tkchu** [comment]
@DEAGS3000 当然，任何优化都有助益。建议fork一份后加入自己润色翻译，再merge进主分支。
