### ISSUE TITLE
为什么format.py生成的html中的代码没有格式化？

### ISSUE THREAD

**Issue by DEAGS3000** [tkchu/Game-Programming-Patterns-CN#12]
调用script/format.py后成功在html目录生成了文件，但是其中的代码是没有格式化的，请问该如何解决？

**Comment by tkchu** [comment]
你需要安装一些format.py中提到的库
$ pip install markdown
$ pip install pygments
$ pip install smartypants

**Comment by DEAGS3000** [comment]
这三个全都安装了，但是生成的HTML中的代码框只有一行，有个横向的滚动条

**Comment by tkchu** [comment]
pygments缺失会造成此项问题。
使用`pip list`指令显示当前的已安装包，以及当前的python版本，贴上来我看一下。

**Comment by DEAGS3000** [comment]
现在好了，就是pygments的问题

**Comment by tkchu** [comment]
很好~

**Comment by Faputa** [comment]
> 现在好了，就是pygments的问题

我遇到了一个同样的问题，能分享一下解决思路吗

**Comment by wumohai** [comment]
您好！我是吴莫海!您给我的邮件我会尽快给您回复。谢谢！
