### ISSUE TITLE
【勘误】序言

### ISSUE THREAD

**Issue by dougen** [tkchu/Game-Programming-Patterns-CN#39]
> 本书的重**返**设计模式一节包含了《设计模式》中的很多模式

返应改为 访

**Comment by xSCx** [comment]
运行的时候显示No module named markdown，MBP，Mojave14.14。4

**Comment by tkchu** [comment]
> 运行的时候显示No module named markdown，MBP，Mojave14.14。4

请按README中的编译本书一节安装依赖包。
