### ISSUE TITLE
这不是 issue，只是感谢！

### ISSUE THREAD

**Issue by lintide** [tkchu/Game-Programming-Patterns-CN#4]
感谢你的翻译工作，比中文纸质书的翻译好得多得多了。再次感谢你的工作！不知道是否可以将这个电子版导出为 epub 或 PDF 等格式？

**Comment by tkchushbm** [comment]
谢谢你的鼓励！
原文使用了脚本对文章进行处理来输出代码和标定格式，因此，导出为其他格式并不是太方便，排版不能尽如人意。（这点对于ePub文件特别明显。我会考虑PDF版本，不过可能要等上一阵子，因为我现在忙于将这些模式应用到我现在开发的游戏中。）

另外，如果有能力，还望您能支持纸质版。
虽然我没有参与纸质版的翻译，他们的翻译某些部分确实不符合原文，但均为小节，无伤大雅。应该对出版社引进和翻译外文好书的行为表示支持。

再次感谢你的支持！

**Comment by klkucan** [comment]
纸质书看了一部分，搜索到你的网站，非常感谢这样的贡献。

**Comment by Tillfore** [comment]
感谢。

**Comment by benqy** [comment]
非常感谢!

**Comment by benqy** [comment]
纸质已买..有kindle版么..能看书的时间都在公交上..

**Comment by tiomke** [comment]
非常感谢您的贡献！！

**Comment by STillSB** [comment]
非常感谢您的贡献！

**Comment by zerak** [comment]
非常感谢译者，翻译的质量很不错。
