### ISSUE TITLE
排版错误

### ISSUE THREAD

**Issue by o2chan** [tkchu/Game-Programming-Patterns-CN#5]
字节码这一章解释器模式一段末尾处有一个排版错误，一个aside标签没有正确显示（环境：chrome 55.0.2883.95 (64-bit)，mac os x 10.11.6）

另外这段最后一句，“将这些拼到一起，怎么念？M-A-N。 这就是为什么大多数广泛应用的编程语言不基于解释器模式。 太慢了，也太消耗内存了。” 里，建议M-A-N处使用原文的S-L-O-W，我对照原文之前完全没反应过来这是慢的拼音。。

**Comment by tkchu** [comment]
非常感谢你的反馈，由于处于乡下，修复得慢了一些。
