### ISSUE TITLE
勘误可以在这里汇总一下

### ISSUE THREAD

**Issue by tiomke** [tkchu/Game-Programming-Patterns-CN#7]
什么是好的软件架构？
对我而言，好的设计意味着当我作出改动，整个程序就好像正等着这种改动。 我可以~~加~~**仅**使用几个函数调用完成任务，而代码库本身无需改动。

**Comment by tiomke** [comment]
我们很少遇到优雅表达的问题，一般反而是一堆~~用况~~。 你想要X在Z情况下做Y，在A情况下做W，诸如此类。换言之，一长列不同行为。

We’re rarely presented with an elegant problem. Instead, it’s a pile of use cases. You want the X to do Y when Z, but W when A, and so on. In other words, a long list of different example behaviors.
展现在我们面前的几乎不会是一个优雅的问题，相反，总是一堆实际用例。你想让X在Z的情况下做Y,在A的情况下做W，诸如此类。换句话说，一系列不同的示例行为。

**Comment by tkchu** [comment]
感谢勘误！已经修正。

**Comment by hellokenlee** [comment]
序-如何阅读这本书-第三行：

> 第二部分，重~放~访设计模式，

[http://gpp.tkchu.me/introduction.html](http://gpp.tkchu.me/introduction.html)

**Comment by tkchu** [comment]
@hellokenlee 已修正，感谢勘误！

**Comment by yangruihan** [comment]
[状态模式](http://gpp.tkchu.me/state.html)一章，状态模式这一节中，这里应该有内容遗失：
<img width="812" alt="1" src="https://user-images.githubusercontent.com/7806458/29003748-536cde5e-7aef-11e7-9f75-f0d57bf03ac7.png">

**Comment by yangruihan** [comment]
作者你好，[游戏循环](http://gpp.tkchu.me/game-loop.html#动机)章节，这里有遗漏：
![123](https://user-images.githubusercontent.com/7806458/29180103-48c6f42a-7e29-11e7-8356-1c95aab0c5c0.png)
应该是事件循环吧

**Comment by tkchu** [comment]
@yangruihan 已修复，感谢勘误

**Comment by yangruihan** [comment]
作者你好，[子类沙箱](http://gpp.tkchu.me/subclass-sandbox.html)章节，这里有错误：
![wx20170815-210632](https://user-images.githubusercontent.com/7806458/29317258-a3ddbc36-81fd-11e7-9a05-f0dd29a3ab0c.png)

**Comment by tkchu** [comment]
@yangruihan 已修复，感谢勘误~

**Comment by yangruihan** [comment]
作者你好，[组件模式](http://gpp.tkchu.me/component.html#快刀斩乱麻)章节，这里翻译可能有误：

- 原文
![wx20170816-133117](https://user-images.githubusercontent.com/7806458/29348598-7985ab30-8287-11e7-862a-9c795d0a5e29.png)

- 译文
![wx20170816-133141](https://user-images.githubusercontent.com/7806458/29348603-80bbde60-8287-11e7-9f96-d18af72c7488.png)

**Comment by tkchu** [comment]
@yangruihan 感谢勘误，这里原文用了亚历山大挥刀斩结的典故，但考虑的国内读者不是很熟悉这个典故，所以替换成了一个俗语，快刀斩乱麻。

**Comment by yangruihan** [comment]
作者你好，[组件模式](http://gpp.tkchu.me/component.html#see-also)章节，这里是不是多了一个`See Also`：
![1](https://user-images.githubusercontent.com/7806458/29360583-314552b0-82b6-11e7-820b-7aad2ce75af6.png)

**Comment by tkchu** [comment]
@yangruihan 已修复，感谢勘误

**Comment by yangruihan** [comment]
作者你好，[服务提供器](http://gpp.tkchu.me/service-locator.html#服务的服务范围有多大？)章节，这里标点错误：
![12](https://user-images.githubusercontent.com/7806458/29528242-ec8398e6-86cd-11e7-9085-729808aed846.png)

**Comment by tkchu** [comment]
@yangruihan 已修复

**Comment by yangruihan** [comment]
作者你好，[对象池](http://gpp.tkchu.me/object-pool.html#模式)章节，这里有错误：
![1](https://user-images.githubusercontent.com/7806458/29627749-ad2ea976-8865-11e7-850e-19278f5f0ea7.png)

**Comment by tkchu** [comment]
@yangruihan 已修复

**Comment by yume-chan** [comment]
[命令模式](http://gpp.tkchu.me/command.html) 章节，原文

> Outside of the weird world of software where words can mean anything, a “client” is a person

应该是

> 在(((词语可能指代任何东西的)诡异的)编程世界)之外，“客户”，是一个人`，

的意思，现在的译文

> 在软件之外的狂野世界，词语可以指代任何事物，“客户”是一个人

并不准确

**Comment by yume-chan** [comment]
[命令模式](http://gpp.tkchu.me/command.html) 章节，译文

> 问题在于假设顶层的 `jump()`, `fireGun()` 之类的函数可以找到玩家的角色，然后像操纵木偶一样操纵它。

缺少主语。

**Comment by yume-chan** [comment]
[命令模式](http://gpp.tkchu.me/command.html) 章节，原文

> We pass it in to execute() so that the derived command can invoke methods on an actor of our choice, like so:

应该是

> 我们将其传给 `execute()`，这样派生继承的命令就可以执行(((我们选择的)角色上的)函数)，就像这样：

（用括号对句子进行了分层，以便于理解）

现在的译文

> 我们将其传给execute()，这样可以在命令的子类中添加函数，来与我们选择的角色关联，就像这样：

中 "添加函数" 的表述并不准确。

**Comment by yume-chan** [comment]
[命令模式](http://gpp.tkchu.me/command.html#角色说明) 章节，原文

> Want a more aggressive opponent?

译文

> 想要一个更加有攻击性的同伴？

_opponent_ 是 _对手_ ，不是 _同伴_。（虽然这个问题不影响整体意思）

**Comment by yume-chan** [comment]
[命令模式](http://gpp.tkchu.me/command.html#角色说明) 章节，原文

> In fact, we can even bolt AI onto the player’s character, which can be useful for things like demo mode where the game needs to run on auto-pilot.

译文 

> 事实上，我们甚至可以为玩家角色加上AI， 这在原型阶段，游戏需要自动演示时是很有用的。

_demo mode_  我觉得是在游戏展上展出时之类的演示模式。

**Comment by yume-chan** [comment]
[命令模式](http://gpp.tkchu.me/command.html#撤销和重做) 章节，原文：

> It’s de rigueur in tools that people use to create games.

意思应该是：

> 在((用来(创造游戏)的)工具)中是必不可少的。

当前译文：

> 在人们创造游戏时，这是必不可少的工具。

并不准确。

**Comment by yume-chan** [comment]
[命令模式](http://gpp.tkchu.me/command.html#用类还是用函数？) 章节，原文：

> manual memory management.

手动内存管理。

**Comment by tkchu** [comment]
@yume-chan 已修正，感谢勘误！具体修改可以查看commit历史。
我觉得肯定还有很多不妥之处，建议为每一章开一个issue，现在这个有些长了。
